baseURL = 'https://gtroiani.github.io/'
languageCode = 'en-us'
title = 'Giorgia Troiani'
theme = 'purehugo'
  
 [params]
    index = "about me"
    linkedinName = "gtroiani"
    githubName = "gtroiani"
    hideShareOptions = true
    description = "Linguistics is fun!"

[params.links]
	"Publications" = "/publications"
	#"CV" = "/cv"
	"Resources"= "/resources"
	"Teaching" = "/teaching"
	
[markup.goldmark.renderer]
	unsafe= true
