baseURL = 'https://gtroiani.github.io/'
languageCode = 'en-us'
title = 'Giorgia Troiani'
theme = 'jane'

[author]
	name = "Giorgia Troiani"
	url = "/about"
	
[[menu.main]]             # config your menu          
  name = "About me"
  weight = 10
  identifier = "about"
  pageref = "/about"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  pageref = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  pageref = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  pageref = "/categories/"
[[menu.main]]
  name = "external-link"
  weight = 50
  pageref = "https://gohugo.io"
  
 [params.social]
    a-email = "mailto:your@email.com"
    b-stack-overflow = "http://localhost:1313"
    c-twitter = "http://localhost:1313"
    d-facebook = "http://localhost:1313"
    e-linkedin = "http://localhost:1313"
    f-google = "http://localhost:1313"
    g-github = "http://localhost:1313"
    h-weibo = "http://localhost:1313"
    i-zhihu = "http://localhost:1313"
    j-douban = "http://localhost:1313"
    k-pocket = "http://localhost:1313"
    l-tumblr = "http://localhost:1313"
    m-instagram = "http://localhost:1313"
    n-gitlab = "http://localhost:1313"
    o-goodreads = "http://localhost:1313"
    p-coding = "http://localhost:1313"
    q-bilibili = "http://localhost:1313"
    r-codeforces = "http://localhost:1313"
    s-mastodon = "http://localhost:1313"
    t-youtube = "http://localhost:1313"
    u-twitch = "http://localhost:1313"
